apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hireflow.fullname" . }}-config
data:
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_HOST: {{ include "hireflow.fullname" . }}-postgres
  POSTGRES_PORT: "5432"
  REDIS_HOST: {{ include "hireflow.fullname" . }}-redis
  REDIS_PORT: "6379"
  ALLOWED_HOSTS: "hireflow.example.com,k8s-hireflow-hireflow-441cf68d4b-542252380.us-east-1.elb.amazonaws.com,hireflow-helm-django,localhost,127.0.0.1"
