{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hireflow.fullname" . }}-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ required "database.password is required" .Values.database.password | quote }}
  SECRET_KEY: {{ required "django.secretKey is required" .Values.django.secretKey | quote }}
{{- end }}
