apiVersion: v1
kind: Service
metadata:
  name: {{ include "hireflow.fullname" . }}-django
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "hireflow.fullname" . }}-django
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
