image:
  repository: hireflow
  tag: v4
  pullPolicy: IfNotPresent

django:
  replicaCount: 1

worker:
  replicaCount: 1

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: alb
  host: hireflow.example.com
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'

storage:
  postgres:
    size: 10Gi
    existingClaim: ""

  media:
    size: 10Gi
    existingClaim: ""
